basePath: /
definitions:
  models.AddDivisionModel:
    properties:
      description:
        type: string
      name:
        type: string
    type: object
  models.DeleteDivisionModel:
    properties:
      to:
        description: |-
          ID of the target division that move all the deleted division's holes to
          default to 1
        type: integer
    type: object
  models.Division:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      pinned:
        description: pinned holes in given order
        items:
          type: integer
        type: array
      updatedAt:
        type: string
    type: object
  models.ModifyDivisionModel:
    properties:
      description:
        type: string
      name:
        type: string
      pinned:
        items:
          type: integer
        type: array
    type: object
  utils.MessageModel:
    properties:
      message:
        type: string
    type: object
info:
  contact:
    email: hasbai@fduhole.com
    name: Maintainer Shi Yue
  description: A anonymous bbs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Tree Hole
  version: 2.0.0
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.MessageModel'
  /divisions:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Division'
            type: array
      summary: List Divisions
      tags:
      - Division
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.AddDivisionModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Division'
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Division'
      summary: Add A Division
      tags:
      - Division
  /divisions/{id}:
    delete:
      description: Delete a division and move all of its holes to another given division
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.DeleteDivisionModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Division'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.MessageModel'
      summary: Delete A Division
      tags:
      - Division
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Division'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.MessageModel'
      summary: Get Division
      tags:
      - Division
    put:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: json
        in: body
        name: json
        required: true
        schema:
          $ref: '#/definitions/models.ModifyDivisionModel'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Division'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.MessageModel'
      summary: Modify A Division
      tags:
      - Division
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
